# Generated by Django 5.0.7 on 2024-07-30 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="커스터 마이징",
                        max_length=30,
                        null=True,
                        verbose_name="채팅방 이름",
                    ),
                ),
            ],
        ),
    ]
