# Generated by Django 5.0.7 on 2024-08-01 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessagesModel",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
